version: '3'

services:
  team-catalog.vue:
    image: elitonluiz1989/vue

    container_name: team-catalog.vue

    ports:
      - "8080:8080"

    volumes:
      - .:/app

    working_dir: /app

  team-catalog.php:
    image: elitonluiz1989/php

    container_name: team-catalog.php

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    working_dir: /app

  team-catalog.mysql:
    image: mysql

    container_name: team-catalog.mysql

    ports:
      - "3306:3306"

    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=team-catalog
      - MYSQL_USER=elitonluiz
      - MYSQL_PASSWORD=secret