version: '3'

services:
  team-catalog.php:
    image: elitonluiz1989/php

    container_name: team-catalog.php

    ports:
      - "8000:8000"

    volumes:
      - .:/app
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./docker/logs/xdebug:/var/logs/xdebug

    working_dir: /app

    command: "php artisan serve --host=0.0.0.0 --port=8000"

  team-catalog.mysql:
    image: mysql

    container_name: team-catalog.mysql

    ports:
      - "3306:3306"

    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=team_catalog
      - MYSQL_USER=elitonluiz
      - MYSQL_PASSWORD=secret
